Solve undef error from a missing compiler application
The following error:
```
error: supervisor: {local,ejabberd_sup}, errorContext: start_error, reason: {undef,[{compile,forms,[[{attribute,1,module,...},{attribute,2,...},{function,...}],[]],[]},{dynamic_compile,from_string,2,[{file,[...]},{line,...}]},{ejabberd_router,compile_routing_module,0,[{file,...},{...}]},{ejabberd_router,init,1,[{...}|...]},{gen_server,init_it,2,[...]},{gen_server,init_it,...}|...]}, offender: [{pid,undefined},{id,ejabberd_router},{mfargs,{ejabberd_router,start_link,[]}},{restart_type,permanent},{shutdown,brutal_kill},{child_type,worker}]
```
was strangely causing errors in Travis. Seems like adding the compiler
app to the release applications as defined in the rebar.config.script
does fix the issue.